"""Day-strip image unit: panel-art sizing, prompts, and the strip resolver.

The per-module logic of spec §7.5 for the §9 day-strip panels. Unlike the
transparent 60×60 Calendar/Chores icons, strip art is a full-bleed opaque
scene: displayed as-is with ``object-fit: cover`` filling the whole panel body
(the store's per-module policy skips chroma keying and the crop). The today
panel shows an "excited" variant generated by *editing* the base art's PNG
(the store's edit-from-base policy), mirroring the §12 countdown hero, so the
excited art keeps the base's subject and composition.

Note: like the countdown hero, the excited variant is not auto-regenerated
when the base image changes (e.g. an admin prompt edit + regenerate on the
base). Regenerating the variant record from the admin page re-edits from the
current base.
"""

from collections.abc import Callable, Mapping, Sequence
from dataclasses import replace

from flask import current_app, url_for

from app.config import get_settings
from app.images.calendar_icons import IconItem, RenderedImage
from app.images.db import ImageSpec
from app.images.generate import DEFAULT_IMAGE_MODEL
from app.images.store import ensure_images

# Keep in sync with the per-module policies in app/images/store.py: the module
# string opts strip art out of keying (_UNKEYED_MODULES), and (module, variant)
# marks the excited record as an edit of its base (_EDIT_FROM_BASE).
DAY_STRIP_MODULE = "DayStrip"
EXCITED_VARIANT = "excited"

# Logical display box (px): square, sized to the day panels' bodies (§9.1 -
# normal 197×147, today 260×157), which the art cover-fills; the exact aspect
# is uncritical because the panel crops the overflow. Drives the generation
# size (clamped into the API bounds, §7.2); the stored PNG keeps its native
# generation resolution, and being unkeyed it stays exactly square - the
# two-event tear layout's coverage math relies on that (day_strip.css).
STRIP_ICON_W = 200
STRIP_ICON_H = 200

type StripIconRequest = tuple[IconItem, bool]
"""One §9.2 strip pick's image inputs: ``(item, excited)``.

The item is the shared ``(title, icon_description)`` pair (§6.4/§7.1); the
flag asks for the excited today-panel variant of that item's art.
"""

type StripIconResolver = Callable[
    [Sequence[StripIconRequest]], Mapping[tuple[str, bool], str | None]
]
"""Maps strip requests to servable art URLs (``None`` per failed item), keyed
by ``(logical key, excited)`` - the logical key is ``icon_description or
title`` (§7.1).

Keyed by the pair, not the key alone: a recurring event can land on today
(excited) and another day (base) in the same render, so one logical key
legitimately resolves to two URLs. Batch-shaped so a render's missing art can
generate concurrently (:func:`app.images.store.ensure_images`).
"""

# The user-authored prompt template for day-strip panel art: the calendar-icon
# template reworked for a full-bleed opaque scene (no chroma-key background -
# this module is unkeyed). The palette table mirrors the §5.3 halftone
# swatches so generations quantize well on the panel (§5.4).
_PROMPT_TEMPLATE = """\
Create a small square illustration that will represent the concept of “{title}” \
on a children’s calendar.  The illustration should be in the style of a comic \
book, with thick black outlines and flat colored fills, emulating a hand-drawn \
comic.  It should be fun and engaging for a 7 year old kid.

The illustration must fill the whole frame edge to edge (full bleed), but the \
main subject must be kept small and centered, taking up only the middle of the \
frame: fit the entire subject within the central 40% of the image, both \
horizontally and vertically, sitting right in the middle.  Reserve a wide outer \
margin — roughly the outer 30% on every side (top, bottom, left, and right) — \
for plain, generic background only, with no part of the main subject entering \
that outer band.  This matters because the outer edges of the image are cropped \
away when it is displayed inside its frame, so only the central region stays \
visible and the subject must fall entirely inside it.  Do not draw a panel \
border, outline, or margin around the scene; a frame is added separately.

It will be shown small (about 200px square), so use big, bold, flat-filled \
shapes with pure saturated primary colors and no fine details.

{elaboration}

There should be no text in the image.

This illustration will be presented on a color e-ink display with a limited \
palette.  You should strive to only use the following colors:
| Swatch | Recipe |
|---|---|
| Black | 100% black |
| White | 100% white |
| Red | 100% red |
| Yellow | 100% yellow |
| Green | 100% green |
| Blue | 100% blue |
| Orange | 50% red 50% yellow |
| Lime | 50% green 50% yellow |
| Teal | 50% blue 50% green |
| Periwinkle | 35% red 65% blue |
| Steel blue | 85% blue 15% black |
| Pink | 35% red 65% white |
| Light-blue (sky) | 40% blue 60% white |
| Mint | 40% green 60% white |
| Cream / tan | 30% yellow 5% red 65% white |
| Light gray | 20% black 80% white |
| Mid gray | 50% black 50% white |
| Dark gray | 75% black 25% white |
| Navy | 70% blue 30% black |
| Maroon | 70% red 30% black |
| Forest green | 65% green 35% black |
| Amber | 30% red 70% yellow |
| Coral | 55% red 45% white |
| Butter | 40% yellow 60% white |

Avoid purple and brown hues.  They do not render well.\

Finally, use a single flat, solid background color behind the scene (it fills \
the panel, so pick one that contrasts with the art).
"""

# The edit prompt for the excited today variant: applied to the base art's
# PNG. The countdown hero's excited edit (§12) plus a no-fine-details guard —
# at panel size, busy modifications turn to noise.
_EXCITED_PROMPT = """\
Change this image to indicate great excitement and anticipation, using the design \
language of comic books: action lines, speed lines, sparkles, and energy bursts.  \
The modifications should be big and bold, with no fine details, fine shapes, or \
fine lines.  Keep the same subject and composition and do not add any text.
"""


def strip_icon_prompt(title: str, icon_description: str | None = None) -> str:
    """The generation prompt for a day-strip panel's art (spec §7.5, §9.1).

    Like the calendar-icon prompt, a set ``icon_description`` (§6.4) does not
    replace the title: it fills the template's mid-template elaboration
    paragraph - the concept stays the event while the description steers the
    artwork.
    """
    prompt = _PROMPT_TEMPLATE.format(title=title, elaboration=icon_description or "")
    # An absent description leaves the elaboration paragraph empty; collapse
    # the doubled paragraph break it leaves behind.
    return prompt.replace("\n\n\n\n", "\n\n")


def excited_strip_prompt() -> str:
    """The edit prompt turning base strip art into its excited variant (§9.1)."""
    return _EXCITED_PROMPT


def make_strip_icon_resolver(collected: list[RenderedImage]) -> StripIconResolver:
    """Build the day-strip art resolver (module ``DayStrip``) for this request.

    Must be called (and the resolver used) inside a request context. Each call
    resolves a whole batch in two phases: every request's base art first (one
    :func:`app.images.store.ensure_images` call, missing images generating
    concurrently), then the excited variants of the today picks in a second,
    sequential call - never batched with the bases, because a variant's
    generation reads its base's PNG from disk (the store's edit-from-base
    policy). A variant miss falls back to the base URL; a base miss yields
    ``None`` for both (the §7.3 fallback chip). Every successfully resolved
    image is appended to ``collected`` for the ``?debug_images=1`` listing
    (§3.5).
    """
    settings = get_settings()
    storage_root = current_app.config["APP_STORAGE_PATH"]
    generate = current_app.config["GENERATE_IMAGE_BYTES"]
    model = settings.module_model_tiers.get(DAY_STRIP_MODULE, DEFAULT_IMAGE_MODEL)

    def ensure_batch(
        batch: Sequence[tuple[ImageSpec, str]],
    ) -> dict[str, str | None]:
        """Ensure a batch, collect successes, and map logical key to URL."""
        if not batch:  # e.g. no today picks, so no excited edits
            return {}
        image_ids = ensure_images(
            batch,
            storage_root=storage_root,
            generate=generate,
            api_key=settings.openai_api_key,
            model=model,
        )
        urls: dict[str, str | None] = {}
        for (spec, _), image_id in zip(batch, image_ids, strict=True):
            if image_id is None:
                urls[spec.item_description] = None
                continue
            rendered = RenderedImage(id=image_id, spec=spec)
            if rendered not in collected:
                collected.append(rendered)
            urls[spec.item_description] = url_for(
                "images.generated_image", image_id=image_id
            )
        return urls

    def resolve(
        requests: Sequence[StripIconRequest],
    ) -> dict[tuple[str, bool], str | None]:
        # Dedupe preserving order, by logical key (§7.1): a repeated key (a
        # recurring event across the week) is one logical base image, and the
        # first occurrence's prompt seeds the record if it is new. The empty
        # guard keeps event-less renders from ever touching storage.
        unique: dict[str, IconItem] = {}
        excited_keys: dict[str, None] = {}
        for item, excited in requests:
            title, icon_description = item
            key = icon_description or title
            unique.setdefault(key, item)
            if excited:
                excited_keys.setdefault(key, None)
        if not unique:
            return {}
        base_specs = {
            key: ImageSpec(
                module=DAY_STRIP_MODULE,
                item_description=key,
                width=STRIP_ICON_W,
                height=STRIP_ICON_H,
            )
            for key in unique
        }
        base_urls = ensure_batch(
            [
                (base_specs[key], strip_icon_prompt(title, icon_description))
                for key, (title, icon_description) in unique.items()
            ]
        )
        excited_urls = ensure_batch(
            [
                (
                    replace(base_specs[key], variant=EXCITED_VARIANT),
                    excited_strip_prompt(),
                )
                for key in excited_keys
                if base_urls[key] is not None  # no base to edit from
            ]
        )
        resolved: dict[tuple[str, bool], str | None] = {}
        for item, excited in requests:
            title, icon_description = item
            key = icon_description or title
            if excited:
                # A variant miss falls back to the base art.
                resolved[(key, True)] = excited_urls.get(key) or base_urls[key]
            else:
                resolved[(key, False)] = base_urls[key]
        return resolved

    return resolve
