"""Pack palette indices into the Inkplate `image.draw` buffer / C header.

Format (verified against ``drawBitmap3Bit`` in the Inkplate library and the
shipped Image Converter example header): 4 bits per pixel, two pixels per
byte, high nibble = left/even-x pixel, rows top-to-bottom with a stride of
``ceil(w / 2)`` bytes. Each nibble is ``palette_index << 1`` — the device does
``nibble >> 1`` and maps the index to its raw panel code internally, so raw
``INKPLATE_*`` codes must never be packed here.
"""

import numpy as np
from numpy.typing import NDArray

from app.eink.palette import WHITE

_BYTES_PER_LINE = 24


def pack_pixels(indices: NDArray[np.uint8]) -> bytes:
    """Pack an (h, w) array of palette indices into the 4bpp device buffer."""
    if indices.ndim != 2:
        raise ValueError(f"expected (h, w) index array, got shape {indices.shape}")
    if indices.max(initial=0) > 5:
        raise ValueError("palette indices must be in 0..5")
    if indices.shape[1] % 2:
        pad = np.full((indices.shape[0], 1), WHITE, dtype=np.uint8)
        indices = np.concatenate([indices, pad], axis=1)
    nibbles = (indices << 1).astype(np.uint8)
    packed = (nibbles[:, 0::2] << 4) | nibbles[:, 1::2]
    return packed.tobytes()


def emit_header(packed: bytes, width: int, height: int, name: str = "mockup") -> str:
    """Render the packed buffer as a C header for the demo Arduino sketch."""
    expected = ((width + 1) // 2) * height
    if len(packed) != expected:
        raise ValueError(
            f"buffer is {len(packed)} bytes, expected {expected} for {width}x{height}"
        )
    lines = [
        f"// Generated by `uv run python -m app.eink` — {width}x{height}, 4bpp,",
        f"// {(width + 1) // 2} bytes/row, {len(packed)} bytes. Do not edit or commit.",
        "#pragma once",
        "#include <Arduino.h>",
        "",
        f"const uint8_t {name}[] PROGMEM = {{",
    ]
    for start in range(0, len(packed), _BYTES_PER_LINE):
        chunk = packed[start : start + _BYTES_PER_LINE]
        lines.append("".join(f"0x{b:02x}," for b in chunk))
    lines += [
        "};",
        f"const uint16_t {name}_w = {width};",
        f"const uint16_t {name}_h = {height};",
        "",
    ]
    return "\n".join(lines)
