"""Countdown-module image unit: hero sizing, prompts, and the hero resolver.

The per-module logic of spec §7.5 for the §12 countdown hero. Unlike the small
calendar icons, the hero is generated on a solid white background and displayed
as-is — no chroma keying, no crop (the store's per-module policy). At the
hype/peak tiers a second "excited" record is generated by *editing* the base
hero's PNG (the store's edit-from-base policy), so the excited art keeps the
base's subject and composition.

Note: the excited variant is not auto-regenerated when the base image changes
(e.g. an admin prompt edit + regenerate on the base). Regenerating the variant
record from the admin page re-edits from the current base.
"""

from dataclasses import replace

from flask import current_app, url_for

from app.config import get_settings
from app.countdown.view import HeroResolver
from app.event_rows import IconItem
from app.images import ImageSpec, RenderedImage, ensure_image
from app.images.generate import DEFAULT_IMAGE_MODEL

# Keep in sync with the per-module policies in app/images/store.py: the module
# string opts the hero out of keying (_UNKEYED_MODULES), and (module, variant)
# marks the excited record as an edit of its base (_EDIT_FROM_BASE).
COUNTDOWN_MODULE = "Countdown"
EXCITED_VARIANT = "excited"

# Logical display box (px): the countdown panel at its LARGEST display — the
# enlarged excited-and-up box (the module grid cell + 28px horizontally and
# 33px vertically per side, countdown.css). The hero fills the whole panel as
# a background layer (object-fit: cover), tucked under the frame, with the
# title/copy overlaid; the calm tier shows the same image in the plain
# cell-sized panel (a slightly deeper cover crop). Drives the generation size
# (clamped into the API bounds, §7.2); the stored PNG keeps its native
# generation resolution. Keep in sync with static/css/countdown.css.
HERO_W = 554
HERO_H = 366

# The user-authored hero prompt: the calendar-icon template reworked for the
# larger hero scene. Deliberately no palette table and no chroma-key
# background — the hero is displayed as-is on its white background.
_HERO_PROMPT_TEMPLATE = """\
Create an illustration that will represent the concept of “{title}” on \
a children’s calendar.  The illustration should be in the style of comic book, with \
black outlines and colored fills, emulating a hand-drawn comic.  It should be fun \
and engaging for a 7 year old kid.  The image will be displayed at medium size \
on a color e-ink device, so prefer simple color fills and shapes without too \
much fine detail.

{elaboration}

The image should be a full little scene with one clear subject.  Keep the subject \
in the middle and the top and bottom edges simple and mostly background, because a \
title and a caption will be overlaid there.

There should be no text in the image.

Use the color #F4C293 for the skin color of any people in the image.

Finally, use a plain, solid, pure white background.\
"""

# The edit prompt for the excited variant: applied to the base hero's PNG.
_EXCITED_PROMPT = """\
Change this image to indicate great excitement and anticipation, using the design \
language of comic books: action lines, speed lines, sparkles, and energy bursts.  \
Keep the same subject and composition, keep the plain, solid, pure white \
background, and do not add any text.\
"""


def countdown_hero_prompt(title: str, icon_description: str | None = None) -> str:
    """The generation prompt for a countdown hero image (spec §7.5, §12).

    Like the calendar-icon prompt, a set ``icon_description`` (§6.4) fills the
    template's elaboration paragraph rather than replacing the title. Keep the
    elaboration handling in sync with
    ``app.images.calendar_icons.calendar_icon_prompt``.
    """
    prompt = _HERO_PROMPT_TEMPLATE.format(
        title=title, elaboration=icon_description or ""
    )
    # An absent description leaves the elaboration paragraph empty; collapse
    # the doubled paragraph break it leaves behind.
    return prompt.replace("\n\n\n\n", "\n\n")


def excited_hero_prompt() -> str:
    """The edit prompt turning the base hero into its excited variant (§12)."""
    return _EXCITED_PROMPT


def make_countdown_hero_resolver(
    collected: list[RenderedImage],
) -> HeroResolver:
    """Build the countdown hero resolver for the current request.

    Must be called (and the resolver used) inside a request context. The base
    hero is always ensured first — it is also the excited variant's edit
    input — and the variant is ensured in a second, sequential call (never
    batched: its generation reads the base's PNG from disk). A variant miss
    falls back to the base URL; a base miss yields ``None`` (hero omitted,
    §7.3). Every successfully resolved image is appended to ``collected`` for
    the ``?debug_images=1`` listing (§3.5).
    """
    settings = get_settings()
    storage_root = current_app.config["APP_STORAGE_PATH"]
    generate = current_app.config["GENERATE_IMAGE_BYTES"]
    model = settings.module_model_tiers.get(COUNTDOWN_MODULE, DEFAULT_IMAGE_MODEL)

    def ensure(spec: ImageSpec, prompt: str) -> str | None:
        image_id = ensure_image(
            spec,
            prompt,
            storage_root=storage_root,
            generate=generate,
            api_key=settings.openai_api_key,
            model=model,
        )
        if image_id is None:
            return None
        rendered = RenderedImage(id=image_id, spec=spec)
        if rendered not in collected:
            collected.append(rendered)
        return url_for("images.generated_image", image_id=image_id)

    def resolve(item: IconItem, excited: bool) -> str | None:
        title, icon_description = item
        base_spec = ImageSpec(
            module=COUNTDOWN_MODULE,
            # The logical key stays icon_description-or-title (§7.1); only the
            # prompt carries the two parts separately.
            item_description=icon_description or title,
            width=HERO_W,
            height=HERO_H,
        )
        base_url = ensure(base_spec, countdown_hero_prompt(title, icon_description))
        if base_url is None or not excited:
            return base_url
        excited_url = ensure(
            replace(base_spec, variant=EXCITED_VARIANT), excited_hero_prompt()
        )
        return excited_url if excited_url is not None else base_url

    return resolve
